const data = {
  images: [
    {
      _id: 1,
      filename: "Image 1",
      contentType: "image/jpeg",
      imageBase64: "/img/img-1.jpg",
      userId: 1,
      imageCategory: ["Flower", "Outdoor"],
      imageOrientation: "Landscape",
      visited: 0,
    },
    {
      _id: 2,
      filename: "Image 2",
      contentType: "image/jpeg",
      imageBase64: "/img/img-2.jpg",
      userId: 2,
      imageCategory: ["Flower", "Outdoor"],
      imageOrientation: "Landscape",
      visited: 3,
    },
    {
      _id: 3,
      filename: "Image 3",
      contentType: "image/jpeg",
      imageBase64: "/img/img-3.jpg",
      userId: 3,
      imageCategory: ["Flower", "Outdoor"],
      imageOrientation: "Potrait",
      visited: 7,
    },
    {
      _id: 4,
      filename: "Image 4",
      contentType: "image/jpeg",
      imageBase64: "/img/img-4.jpg",
      userId: 4,
      imageCategory: ["Flower", "Indoor"],
      imageOrientation: "Landscape",
      visited: 15,
    },
    {
      _id: 5,
      filename: "Image 5",
      contentType: "image/jpeg",
      imageBase64: "/img/img-5.jpg",
      userId: 5,
      imageCategory: ["Flower", "Outdoor"],
      imageOrientation: "Landscape",
      visited: 5,
    },
    {
      _id: 6,
      filename: "Image 6",
      contentType: "image/jpeg",
      imageBase64: "/img/img-6.jpg",
      userId: 6,
      imageCategory: ["Flower", "Outdoor"],
      imageOrientation: "Landscape",
      visited: 8,
    },
    {
      _id: 7,
      filename: "Image 7",
      contentType: "image/jpeg",
      imageBase64: "/img/img-7.jpg",
      userId: 7,
      imageCategory: ["Flower", "Outdoor"],
      imageOrientation: "Landscape",
      visited: 0,
    },
    {
      _id: 8,
      filename: "Image 8",
      contentType: "image/jpeg",
      imageBase64: "/img/img-8.jpg",
      userId: 8,
      imageCategory: ["Nighlight", "Outdoor"],
      imageOrientation: "Potrait",
      visited: 10,
    },
    {
      _id: 9,
      filename: "Image 9",
      contentType: "image/jpeg",
      imageBase64: "/img/img-9.jpg",
      userId: 9,
      imageCategory: ["Flower", "Outdoor"],
      imageOrientation: "Landscape",
      visited: 11,
    },
    {
      _id: 10,
      filename: "Image 10",
      contentType: "image/jpeg",
      imageBase64: "/img/img-10.jpg",
      userId: 10,
      imageCategory: ["Flower", "Outdoor"],
      imageOrientation: "Landscape",
      visited: 2,
    },
  ],
  imageIcon: [
    {
      _id: 11,
      src: "/img/ico-popular-search-1.png",
      title: "Restaurant",
    },
    {
      _id: 12,
      src: "/img/ico-popular-search-2.png",
      title: "Hotel",
    },
    {
      _id: 13,
      src: "/img/ico-popular-search-3.png",
      title: "Cinema",
    },
    {
      _id: 14,
      src: "/img/ico-popular-search-4.png",
      title: "Shopping",
    },
  ],
  aboutImage: [
    {
      _id: 15,
      src: "/img/about-6.jpg",
      props: "uk-width-1-1",
    },
    {
      _id: 16,
      src: "/img/about-5.jpg",
      props: "uk-width-2-3",
    },
    {
      _id: 17,
      src: "/img/about-1.jpg",
      props: "uk-width-1-3",
    },
  ],
};

export default data;
